In [1]:
import torch

In [2]:
x = torch.ones((2, 2), requires_grad=True)

In [3]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [4]:
y = x + 2

In [5]:
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [6]:
print(y.grad_fn)

In [7]:
z = y * y * 3
out = z.mean()

In [8]:
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [9]:
a = torch.randn((2, 2))

In [10]:
a = ((a * 3) / (a - 1))

In [11]:
a

tensor([[ 5.9770, -0.6739],
        [ 0.0853,  2.0473]])

In [12]:
print(a.requires_grad)

False


In [13]:
a.requires_grad_(True)

tensor([[ 5.9770, -0.6739],
        [ 0.0853,  2.0473]], requires_grad=True)

In [14]:
b = (a * a).sum()

In [15]:
b

tensor(40.3773, grad_fn=<SumBackward0>)

In [16]:
b.grad_fn

In [18]:
b.backward()

In [19]:
a.grad

tensor([[11.9540, -1.3479],
        [ 0.1707,  4.0945]])

$out = \sum_{ij} \frac{((x_{ij} + 2) \times (x_{ij} + 2) \times 3)}{4}$, $\frac{\partial out}{\partial x_{ij}} = \frac{3}{2}x + 4$

In [20]:
out.backward()

In [21]:
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

In [24]:
x = torch.randn(3, requires_grad=True)

In [25]:
y = x * 2

In [26]:
y

tensor([1.8295, 1.4641, 1.7214], grad_fn=<MulBackward0>)

In [27]:
x

tensor([0.9148, 0.7321, 0.8607], requires_grad=True)

In [29]:
y.data

tensor([1.8295, 1.4641, 1.7214])

In [28]:
y.data.norm()

tensor(2.9076)

In [30]:
while y.data.norm() < 1000:
    y = y * 2
print(y)

tensor([936.7125, 749.6223, 881.3558], grad_fn=<MulBackward0>)


In [32]:
v = torch.tensor([0.1, 1.0, 0.0001])

In [33]:
y.backward(v)

In [34]:
x.grad

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])

In [35]:
print(x.requires_grad)

True


In [36]:
print((x ** 2).requires_grad)

True


In [37]:
with torch.no_grad():
    
    print((x ** 2).requires_grad)

False


In [ ]:
y.view()