In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3)

In [3]:
x

tensor([[-2.6140e-29,  4.5869e-41, -2.6135e-29],
        [ 4.5869e-41, -2.6138e-29,  4.5869e-41],
        [ 1.1351e-43,  0.0000e+00, -9.8343e+02],
        [ 4.5869e-41,  9.1084e-44,  0.0000e+00],
        [-9.8343e+02,  4.5869e-41, -9.8343e+02]])

In [4]:
x = torch.rand(5, 3)

In [5]:
x

tensor([[0.1515, 0.0255, 0.7128],
        [0.8251, 0.6103, 0.0623],
        [0.7775, 0.8625, 0.5515],
        [0.4376, 0.3622, 0.2797],
        [0.1944, 0.0536, 0.5654]])

In [7]:
x.size()

torch.Size([5, 3])

In [10]:
x = torch.zeros([5, 3], dtype=torch.int32)

In [11]:
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [12]:
torch.rand(5, 3).dtype

torch.float32

In [13]:
x = torch.tensor([5.5, 3])

In [14]:
x

tensor([5.5000, 3.0000])

In [15]:
x = x.new_ones((5, 3), dtype=torch.double)

In [16]:
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [17]:
x = torch.randn_like(x, dtype=torch.float32)

In [18]:
x

tensor([[-0.8390,  0.4645, -1.6484],
        [ 0.6195,  1.0093,  0.8752],
        [ 0.2683, -1.2117,  0.6227],
        [-0.5281,  0.1232, -0.2859],
        [ 0.3932,  0.1528,  1.1757]])

In [19]:
y = torch.rand((5, 3))

In [20]:
x + y

tensor([[-0.1238,  1.4402, -1.5907],
        [ 0.8791,  1.1026,  1.0224],
        [ 0.6048, -0.8636,  0.8365],
        [ 0.1388,  0.1419, -0.1462],
        [ 1.2758,  0.4083,  1.4224]])

In [21]:
torch.add(x, y)

tensor([[-0.1238,  1.4402, -1.5907],
        [ 0.8791,  1.1026,  1.0224],
        [ 0.6048, -0.8636,  0.8365],
        [ 0.1388,  0.1419, -0.1462],
        [ 1.2758,  0.4083,  1.4224]])

In [24]:
result = torch.empty((5, 3))
torch.add(x, y, out=result)

tensor([[-0.1238,  1.4402, -1.5907],
        [ 0.8791,  1.1026,  1.0224],
        [ 0.6048, -0.8636,  0.8365],
        [ 0.1388,  0.1419, -0.1462],
        [ 1.2758,  0.4083,  1.4224]])

In [25]:
y.add_(x)

tensor([[-0.1238,  1.4402, -1.5907],
        [ 0.8791,  1.1026,  1.0224],
        [ 0.6048, -0.8636,  0.8365],
        [ 0.1388,  0.1419, -0.1462],
        [ 1.2758,  0.4083,  1.4224]])

In [27]:
y

tensor([[-0.1238,  1.4402, -1.5907],
        [ 0.8791,  1.1026,  1.0224],
        [ 0.6048, -0.8636,  0.8365],
        [ 0.1388,  0.1419, -0.1462],
        [ 1.2758,  0.4083,  1.4224]])

In [28]:
x[:, 1]

tensor([ 0.4645,  1.0093, -1.2117,  0.1232,  0.1528])

In [29]:
x = torch.rand((4, 4))

In [30]:
y = x.view((16, ))

In [31]:
y

tensor([0.8114, 0.7055, 0.5909, 0.9936, 0.4072, 0.1560, 0.8172, 0.5758, 0.9630,
        0.9123, 0.0787, 0.5096, 0.3736, 0.0393, 0.0149, 0.5957])

In [32]:
z = x.view((-1, 8))

In [33]:
z

tensor([[0.8114, 0.7055, 0.5909, 0.9936, 0.4072, 0.1560, 0.8172, 0.5758],
        [0.9630, 0.9123, 0.0787, 0.5096, 0.3736, 0.0393, 0.0149, 0.5957]])

In [34]:
x.size(), y.size(), z.size()

(torch.Size([4, 4]), torch.Size([16]), torch.Size([2, 8]))

In [35]:
x[0, :] = 1

In [36]:
x

tensor([[1.0000, 1.0000, 1.0000, 1.0000],
        [0.4072, 0.1560, 0.8172, 0.5758],
        [0.9630, 0.9123, 0.0787, 0.5096],
        [0.3736, 0.0393, 0.0149, 0.5957]])

In [37]:
y

tensor([1.0000, 1.0000, 1.0000, 1.0000, 0.4072, 0.1560, 0.8172, 0.5758, 0.9630,
        0.9123, 0.0787, 0.5096, 0.3736, 0.0393, 0.0149, 0.5957])

In [38]:
z

tensor([[1.0000, 1.0000, 1.0000, 1.0000, 0.4072, 0.1560, 0.8172, 0.5758],
        [0.9630, 0.9123, 0.0787, 0.5096, 0.3736, 0.0393, 0.0149, 0.5957]])

In [39]:
x = torch.rand((1))

In [40]:
x

tensor([0.8966])

In [41]:
x.item()

0.8965577483177185

In [43]:
torch.get_default_dtype()

torch.float32

In [44]:
a = torch.ones((5, ))

In [45]:
a

tensor([1., 1., 1., 1., 1.])

In [46]:
a.dtype

torch.float32

In [47]:
b = a.numpy()

In [48]:
print(b)

[1. 1. 1. 1. 1.]


In [49]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [50]:
import numpy as np

In [51]:
a = np.ones((5, ))
b = torch.from_numpy(a)
a = np.add(a, 1)

In [52]:
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [57]:
a = np.ones(5)
b = torch.from_numpy(a)
print("Before :{}".format(id(a)))
np.add(a, 1, out=a)
print(a)
print("After :{}".format(id(a)))
print(b)

Before :140589574435904
[2. 2. 2. 2. 2.]
After :140589574435904
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [58]:
a = np.ones((5, ))
b = torch.from_numpy(a)
print("Before :{}".format(id(a)))
a = np.add(a, 1)
print(a)
print("After :{}".format(id(a)))
print(b)

Before :140589574436864
[2. 2. 2. 2. 2.]
After :140589574435904
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [55]:
a.dtype

dtype('float64')

In [59]:
torch.cuda.is_available()

False