In [2]:
import tensorflow as tf

In [3]:
x = tf.ones((2, 2))

In [4]:
x

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [5]:
with tf.GradientTape() as t:
    t.watch(x)
    y = tf.reduce_sum(x)
    z = tf.multiply(y, y)

In [10]:
z

<tf.Tensor: shape=(), dtype=float32, numpy=16.0>

In [8]:
dz_dx = t.gradient(z, x)

In [9]:
dz_dx

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[8., 8.],
       [8., 8.]], dtype=float32)>

In [18]:
with tf.GradientTape() as t:
    t.watch(x)
    y = tf.reduce_sum(x)
    z = tf.multiply(y, y)

In [19]:
t.gradient(y, x)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [20]:
with tf.GradientTape() as t:
    t.watch(x)
    y = tf.reduce_sum(x)
    z = tf.multiply(y, y)

In [21]:
t.gradient(z, y)

<tf.Tensor: shape=(), dtype=float32, numpy=8.0>

In [22]:
with tf.GradientTape() as t:
    y = tf.reduce_sum(x)
    z = tf.multiply(y, y)
    t.watch(y)

In [23]:
t.gradient(z, y)

In [25]:
with tf.GradientTape() as t:
    x = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
    t.watch(x)
    y = tf.multiply(x, x)

In [26]:
t.gradient(y, x)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 4.],
       [6., 8.]], dtype=float32)>

In [28]:
x = tf.constant(3.0)
with tf.GradientTape(persistent=True) as t:
    t.watch(x)
    y = x*x
    z = y*y
dz_dx = t.gradient(z, x)

In [29]:
dz_dx

<tf.Tensor: shape=(), dtype=float32, numpy=108.0>

In [30]:
dy_dx = t.gradient(y, x)

In [31]:
dy_dx

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [33]:
del t

In [35]:
def f(x, y):
    output = 1.0
    for i in range(y):
        if i > 1 and i < 5:
            output = tf.multiply(output, x)
    return output

In [41]:
def grad(x, y):
    with tf.GradientTape() as t:
        t.watch(x)
        out = f(x, y)
        print(out)
    return t.gradient(out, x)

In [42]:
x = tf.constant(2.0)

In [43]:
grad(x, 4)

tf.Tensor(4.0, shape=(), dtype=float32)


<tf.Tensor: shape=(), dtype=float32, numpy=4.0>

In [44]:
grad(x, 5)

tf.Tensor(8.0, shape=(), dtype=float32)


<tf.Tensor: shape=(), dtype=float32, numpy=12.0>

In [45]:
grad(x, 6)

tf.Tensor(8.0, shape=(), dtype=float32)


<tf.Tensor: shape=(), dtype=float32, numpy=12.0>

In [46]:
x = tf.Variable(1.0)
with tf.GradientTape() as t:
    with tf.GradientTape() as t2:
        y = x * x * x
    dy_dx = t2.gradient(y, x)
d2y_dx2 = t.gradient(dy_dx, x)

In [47]:
d2y_dx2

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [48]:
dy_dx

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

In [51]:
x = tf.Variable(2.0)
with tf.GradientTape() as t:
    y = x * x
dy_dx = t.gradient(y, x)

In [52]:
dy_dx

<tf.Tensor: shape=(), dtype=float32, numpy=4.0>

In [57]:
w = tf.Variable([[1.0], [2.0]])
x = tf.constant([[3.0, 4.0]])

In [58]:
tf.matmul(w, x)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[3., 4.],
       [6., 8.]], dtype=float32)>

In [59]:
tf.sigmoid(w + x)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.98201376, 0.9933072 ],
       [0.9933072 , 0.9975274 ]], dtype=float32)>

In [60]:
x = tf.constant(1.0)

In [62]:
x += 2

In [63]:
x

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>