In [1]:
import tensorflow as tf

In [2]:
tf.config.list_logical_devices()

[LogicalDevice(name='/device:CPU:0', device_type='CPU'),
 LogicalDevice(name='/device:XLA_CPU:0', device_type='XLA_CPU'),
 LogicalDevice(name='/device:GPU:0', device_type='GPU'),
 LogicalDevice(name='/device:GPU:1', device_type='GPU'),
 LogicalDevice(name='/device:GPU:2', device_type='GPU'),
 LogicalDevice(name='/device:GPU:3', device_type='GPU'),
 LogicalDevice(name='/device:XLA_GPU:0', device_type='XLA_GPU'),
 LogicalDevice(name='/device:XLA_GPU:1', device_type='XLA_GPU'),
 LogicalDevice(name='/device:XLA_GPU:2', device_type='XLA_GPU'),
 LogicalDevice(name='/device:XLA_GPU:3', device_type='XLA_GPU')]

In [3]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:XLA_CPU:0', device_type='XLA_CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU'),
 PhysicalDevice(name='/physical_device:GPU:1', device_type='GPU'),
 PhysicalDevice(name='/physical_device:GPU:2', device_type='GPU'),
 PhysicalDevice(name='/physical_device:GPU:3', device_type='GPU'),
 PhysicalDevice(name='/physical_device:XLA_GPU:0', device_type='XLA_GPU'),
 PhysicalDevice(name='/physical_device:XLA_GPU:1', device_type='XLA_GPU'),
 PhysicalDevice(name='/physical_device:XLA_GPU:2', device_type='XLA_GPU'),
 PhysicalDevice(name='/physical_device:XLA_GPU:3', device_type='XLA_GPU')]

In the tf.keras.layers package, layers are objects. To construct a layer, simply construct the object. Most layers take as a first argument the number of output dimensions / channels.

The number of input dimensions is often unnecessary, as it can be inferred the first time the layer is used, but it can be provided if you want to specify it manually, which is useful in some complex models.

In [15]:
layer = tf.keras.layers.Dense(10, input_shape=(None, 5))

In [16]:
layer

In [17]:
layer.variables

[]

In [18]:
tf.zeros([10, 5])

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [19]:
layer(tf.zeros([10, 5]))

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [20]:
layer.variables

[<tf.Variable 'dense/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[ 0.5015791 ,  0.39659506, -0.11210299,  0.5405106 , -0.4199321 ,
          0.05797267,  0.5746862 ,  0.05491275, -0.61840606, -0.62446594],
        [-0.34680614,  0.22168249, -0.3430794 , -0.0780251 ,  0.5919836 ,
         -0.62368685, -0.41961876, -0.33990604,  0.13769233,  0.15179896],
        [-0.398329  , -0.13863358,  0.17040664, -0.14238098, -0.3150391 ,
          0.4017896 ,  0.5912011 ,  0.21510929,  0.05304492, -0.4806543 ],
        [ 0.09752196,  0.35443562,  0.15490103,  0.44219607,  0.40868253,
         -0.31777668, -0.10726643, -0.09264714, -0.3524051 , -0.04525316],
        [-0.11131424, -0.23020935,  0.32984978,  0.25538903, -0.53957015,
          0.20717359,  0.3167858 , -0.522952  ,  0.04439777,  0.2798909 ]],
       dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>]

In [21]:
layer.kernel

<tf.Variable 'dense/kernel:0' shape=(5, 10) dtype=float32, numpy=
array([[ 0.5015791 ,  0.39659506, -0.11210299,  0.5405106 , -0.4199321 ,
         0.05797267,  0.5746862 ,  0.05491275, -0.61840606, -0.62446594],
       [-0.34680614,  0.22168249, -0.3430794 , -0.0780251 ,  0.5919836 ,
        -0.62368685, -0.41961876, -0.33990604,  0.13769233,  0.15179896],
       [-0.398329  , -0.13863358,  0.17040664, -0.14238098, -0.3150391 ,
         0.4017896 ,  0.5912011 ,  0.21510929,  0.05304492, -0.4806543 ],
       [ 0.09752196,  0.35443562,  0.15490103,  0.44219607,  0.40868253,
        -0.31777668, -0.10726643, -0.09264714, -0.3524051 , -0.04525316],
       [-0.11131424, -0.23020935,  0.32984978,  0.25538903, -0.53957015,
         0.20717359,  0.3167858 , -0.522952  ,  0.04439777,  0.2798909 ]],
      dtype=float32)>

In [22]:
layer.bias

<tf.Variable 'dense/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>

In [32]:
class MyDenseLayer(tf.keras.layers.Layer):
    def __init__(self, num_outputs):
        super(MyDenseLayer, self).__init__()
        self.num_outputs = num_outputs
    
    def build(self, input_shape):
        print("input_shape: {}".format(input_shape))
        self.kernel = self.add_weight("kernel", shape=[int(input_shape[-1]), self.num_outputs])
    
    def call(self, input):
        print("call")
        return tf.matmul(input, self.kernel)

In [33]:
layer = MyDenseLayer(10)

In [34]:
a = layer(tf.zeros([10, 5]))

input_shape: (10, 5)
call


In [35]:
[item for item in layer.trainable_variables]

[<tf.Variable 'my_dense_layer_2/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[-3.27451617e-01,  3.61914337e-01, -3.37323159e-01,
         -6.35721087e-02, -4.26254839e-01,  6.06413782e-01,
         -6.24180675e-01, -6.28009677e-01, -4.96960461e-01,
          5.43825090e-01],
        [ 1.72869027e-01, -4.38249528e-01,  5.80462396e-01,
          5.25549591e-01, -3.24966311e-01,  5.89348733e-01,
         -4.37051475e-01, -3.83297741e-01, -2.97757387e-02,
         -1.01536870e-01],
        [ 2.27073073e-01,  1.52906239e-01, -4.76093054e-01,
         -8.15764666e-02,  1.95330918e-01, -1.51260048e-01,
         -5.45390785e-01, -6.32875562e-02,  3.34866643e-01,
          1.65864289e-01],
        [ 2.32721925e-01,  2.90500879e-01,  1.28492236e-01,
          1.85966134e-01, -3.15647066e-01,  3.03999960e-01,
         -6.45021796e-02,  1.88506067e-01,  4.71353531e-04,
         -1.89095020e-01],
        [ 4.62335944e-02,  5.55158794e-01, -1.57822251e-01,
         -1.28471851e-03,  1.21151

In [36]:
[item.shape for item in layer.trainable_variables]

[TensorShape([5, 10])]

In [37]:
[item.shape for item in layer.variables]

[TensorShape([5, 10])]