In [1]:
import tensorflow as tf

In [2]:
import numpy as np

In [3]:
tf.add(1, 2)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [4]:
tf.add(np.array(1), np.array(2))

<tf.Tensor: shape=(), dtype=int64, numpy=3>

In [5]:
tf.add([1, 2, 3, 4], 9) # support broadcasting

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([10, 11, 12, 13], dtype=int32)>

In [6]:
tf.square([1, 2, 3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 9], dtype=int32)>

In [7]:
a = tf.Variable([[1, 2, 3], [4, 5, 6]])

In [8]:
a.shape

TensorShape([2, 3])

In [9]:
tf.reduce_sum(a)

<tf.Tensor: shape=(), dtype=int32, numpy=21>

In [10]:
tf.reduce_sum(a, 0)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 7, 9], dtype=int32)>

In [11]:
tf.reduce_sum(a, 1)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 6, 15], dtype=int32)>

In [13]:
tf.matmul([[1]], [[2, 3]])

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[2, 3]], dtype=int32)>

In [14]:
ndarray = np.ones([3, 3])

TensorFlow operations convert numpy arrays to Tensors automatically

In [15]:
tensor = tf.multiply(ndarray, 42)

In [16]:
print(tensor)

tf.Tensor(
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]], shape=(3, 3), dtype=float64)


And NumPy operations convert Tensors to numpy arrays automatically

In [17]:
np.add(tensor, 1)

array([[43., 43., 43.],
       [43., 43., 43.],
       [43., 43., 43.]])

The .numpy() method explicitly converts a Tensor to a numpy array

In [18]:
tensor.numpy()

array([[42., 42., 42.],
       [42., 42., 42.],
       [42., 42., 42.]])

In [19]:
x = tf.random.uniform([3, 3])

In [20]:
print("Is there a GPU available: "),
print(tf.config.experimental.list_physical_devices("GPU"))

Is there a GPU available: 
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU'), PhysicalDevice(name='/physical_device:GPU:1', device_type='GPU'), PhysicalDevice(name='/physical_device:GPU:2', device_type='GPU'), PhysicalDevice(name='/physical_device:GPU:3', device_type='GPU')]


In [22]:
x.device

'/job:localhost/replica:0/task:0/device:GPU:0'

In [23]:
import time

In [30]:
def time_matmul(x):
    s = time.time()
    for _ in range(1000):
        tf.matmul(x, x)
    t = time.time() - s
    print("{} s".format(t))

In [31]:
with tf.device("CPU:0"):
    x = tf.random.uniform((1000, 1000))
    assert x.device.endswith("CPU:0")
    time_matmul(x)

3.6500747203826904 s


In [34]:
if tf.config.experimental.list_physical_devices("GPU"):
    print("On GPU")
    with tf.device("GPU"):
        x = tf.random.uniform((1000, 1000))
#         assert x.device.endswith("GPU")
        time_matmul(x)

On GPU
0.10023951530456543 s


In [36]:
ds_tensors = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5])

In [37]:
ds_tensort_tmp1 = ds_tensors.map(tf.square)

In [38]:
for item in ds_tensort_tmp1:
    print(item)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(16, shape=(), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)


In [39]:
ds_tensor_tmp2 = ds_tensors.map(tf.square).shuffle(2).batch(2)

In [40]:
for item in ds_tensor_tmp2:
    print(item)

tf.Tensor([1 9], shape=(2,), dtype=int32)
tf.Tensor([ 4 16], shape=(2,), dtype=int32)
tf.Tensor([25], shape=(1,), dtype=int32)
